### ISSUE TITLE
React not bails out in the case props not changed

### ISSUE THREAD

**Issue by MHA15** [reactjs/rfcs#149]
> The funny thing is that React already does this, except a level shallower than memo. React already bails out by default if `oldProps === newProps`. I.e. if the props object itself is the same. This is ofc much less common to match but it's also significantly cheaper to do.

_Originally posted by @sebmarkbage in https://github.com/reactjs/rfcs/pull/108#issuecomment-468888951_

Thanks for that you mentioned this point but why [this sandbox](https://codesandbox.io/s/upbeat-snowflake-u04fv) not work as like you said? I checked the props in child element and they are not equal to props I send to `React.createElement` ! why ?

And at the last please tell us where can we find all of these rules and points to better understand what is going on behind react

**Comment by illuminist** [comment]
Because `newProps.children !== oldProps.children`.

Wrapping `Child` with `React.memo` will make sure that child element will stay the same as previous props given same props for the Child.

**Comment by MHA15** [comment]
> Because `newProps.children !== oldProps.children`.
> 
> Wrapping `Child` with `React.memo` will make sure that child element will stay the same as previous props given same props for the Child.

the above example doesn't have any children props and I think `props.children == undefined` and is equal between multiple renders

**Comment by illuminist** [comment]
There are the children of React.Fragment(`<>{children}</>`).

**Comment by Eddie-CooRo** [comment]
@MHA15 I thinks that's because React creates a new prop object every time the `React.createElement` gets called. You can check that for yourself [here](https://github.com/facebook/react/blob/9751935abfa5585623f3ee85bb3c4eff4154e376/packages/react/src/ReactElement.js#L352)
But I still don't quite understand where the `oldProps === newProps` check that @sebmarkbage has talked about would be useful. (maybe some internal code paths where an already existing fiber gets re-rendered?)
