### ISSUE TITLE
[Hooks] useComponent - alternative to return

### ISSUE THREAD

**Issue by brianblakely** [reactjs/rfcs#78]
One issue with hooks is that `useEffect` happens after `return` (i.e. render), but it **must** come first in code order by virtue of how functions work.

It would be nice to optionally omit the `return` while introducing a `useComponent` hook that can be included anywhere within a component body.

```jsx
function DisplayCount(props) {
  const [count] = useState();

  useComponent(<div>{count}</div>);

  useEffect(()=> {
    doSomethingAfterRender();
  });
}
```

This precludes us from branched rendering (aside from inline statements), but hopefully conditional blocks come to hooks one day.

**Comment by TryingToImprove** [comment]
I think that `return` is a great solution to make component since it is possible to have a single component, and if the component returns more than 1 component we already have `Fragment´.

Having `useComponent` will like cause a lot of confusing about what is actually rendered, and since people can share "custom hooks", a developer will never actually know what is rendered and where it is rendered.

**Comment by brianblakely** [comment]
@TryingToImprove Custom hooking is a very valid concern.

Otherwise, it's worth noting that `return` is quite restrictive compared to hooks, and tying rendering to that seems a little arbitrary to me.

**Comment by Kovensky** [comment]
```js
const result = (<>
  {/* contents */
</>)

useEffect(() => { /* ... */ })

return result
```

😇

**Comment by brianblakely** [comment]
@Kovensky That's kind of a neat pattern.

**Comment by gaearon** [comment]
Hi, thanks for your suggestion. RFCs should be submitted as pull requests, not issues. I will close this issue but feel free to resubmit in the PR format.
