### ISSUE TITLE
[Hooks] Alternative useCallback implementation

### ISSUE THREAD

**Issue by gokalina** [reactjs/rfcs#83]
According to this [page](https://reactjs.org/docs/hooks-reference.html#usecallback) `useCallback(fn, inputs)` is equivalent to `useMemo(() => fn, inputs)`

I suggest another one (implemented with current hooks):

```javascript
function useHandler(handler) {
  const holder = useRef();
  holder.current = handler;

  // TODO: avoid useMemo?
  return useMemo(
    () =>
      function(...args) {
        return holder.current.apply(this, args);
      },
    []
  );
}
```

It has advantages:
* no need to specify `inputs`, latest instance of `handler` will be called
* result of `useHandler` is constant for all rerenders

**Comment by gaearon** [comment]
Yeah, we've considered this. It's not clear however what pitfalls this would have in concurrent mode. The particular implementation you propose would definitely have issues (because it mutates during rendering). The one using an effect (like in our FAQ) would be a bit safer but isn't generic purpose (it requires the tree to commit first) and might also have pitfalls.

We have another idea for how to solve this. I described it briefly in https://github.com/facebook/react/issues/14099 and might add more info there later. Please participate in that issue if you're interested. Thanks!

**Comment by ypresto** [comment]
For someone searching for what is "async-safe" or "mutation of ref during rendering", it is described here:
https://github.com/facebook/react/issues/14099#issuecomment-436647120

**Comment by LiuJi-Jim** [comment]
Looks like [ahooks/usePersistFn](https://github.com/alibaba/hooks/blob/master/packages/hooks/src/usePersistFn/index.ts)

**Comment by duj26089** [comment]
> 看起来像[ahooks/usePersistFn](https://github.com/alibaba/hooks/blob/master/packages/hooks/src/usePersistFn/index.ts)

大佬也研究react么

**Comment by gaearon** [comment]
We've submitted a proposal to solve that's largely similar (but works a bit differently). Would appreciate your input.

https://github.com/reactjs/rfcs/pull/220
