### ISSUE TITLE
[hooks][test]Provide a way to test component without mock the effect/global state?

### ISSUE THREAD

**Issue by TotooriaHyperion** [reactjs/rfcs#93]
Any way to make Function Component _**Pure**_ for unit testing?

Or what's the right pattern and best practice to draw a proper line between pure function and component instance that make test meaningful & useful?

**Comment by TotooriaHyperion** [comment]
@oriSomething when useContext(xxx) / useEffect(subscribeToWindowResize)
needs to provide a context/window.
then the bugs in context would cause component's test fail, making it a chaos finding bug in large app.
I'm just want to follow the basic rules of unit test.
Or should stateful component be tested by integrate test?
It's not a good idea about Component as a Function.
useContext/useEffect just makes the Component implicitly has more data source though it makes code declarative.
It's better to specify global state/effect/event in terms of a simple object and then let the real effect be performed by the renderer.
And then split the Component into template + state-provider.
Then we can
1.Test the template with simply give it a input and trigger a event, then deepEqual the event with expect.
2.Test the state-provider with simply run it with a input and get the effect descriptions and deepEqual the descriptions with expect.
3.Test the context/customHooks isolate.

So we can split a integrate test with many implicit dependencies on global state into parts of clear, simple, reliable, framework compatible unit test.

**Comment by oriSomething** [comment]
- For `useContext`, you can just mock the context or just giving a mock for the value of the context provider. (or even create `useMyAwesomeContext` and mock this function)
- For `useEffect` what is the different for you when you're testing a regular component?
- You better mock `subscribeToWindowResize` or even better create `useWindowSize` hook and mock it
- I don't know the what is the specific component you're testing. But for me, for most tests `ReactTestRender` + `JSDOM` do the job
- Calling a function component instead of using React itself for testing the function component, seems to me like a mistake. Because it's almost always do a bit different things, And for me, it's not logical, to mock everything React does to test React component

**Comment by TotooriaHyperion** [comment]
I just want to **_avoid mocking anything_**.
I want to test without any mocking.
Input **_simple object_**, output **_simple object_**.
Test with equal & deepEqual only these two assertion.

What I  want to do is using ReactTestRender to test only the render result (as old React.SFC).

And testing all the other things by making every function pure.

**Comment by buhichan** [comment]
I think you should give a sample about what you're talking about, no idea what you mean.

**Comment by gaearon** [comment]
Hooks should work just fine with ReactTestRenderer. You can specify context for test the way you normally do. Please provide a full example so we can discuss it. Ideally, also provide an example of how you’d test an equivalent class component. Then we can compare them.

**Comment by morlay** [comment]
Mocking is not necessary. 
But there is something confused when use `useEffect` in `jsdom` env

@gaearon @buhichan 
https://github.com/facebook/react/issues/14354
```
import React from "react";
import { render } from "react-dom";
import { useState, useLayoutEffect, useEffect } from "react";

function App() {
  const [mounted, setMount] = useState("");

  useEffect(() => {
    console.log("App effect");
    setMount(s => s + "App mounted;");
  }, []);

  useLayoutEffect(() => {
    console.log("App layout effect");
    setMount(s => s + "App layout mounted;");
  }, []);

  return <div>{mounted}</div>;
}

function App2() {
  const [mounted, setMount] = useState("");

  useEffect(() => {
    console.log("App2 effect");
    setMount(s => s + "App2 mounted;");
  }, []);

  useLayoutEffect(() => {
    console.log("App2 layout effect");
  }, []);

  return <div>{mounted}</div>;
}

test("test App", () => {
  const node = mount(<App />);
  console.log("mounted", node.innerHTML);
});

test("test App2", () => {
  const node = mount(<App2 />);
  console.log("mounted", node.innerHTML);
});

function mount(e) {
  const node = document.createElement("div");
  render(e, node);
  return node;
}
```
useEffect's callback is not always fired in same time.

expect 

```
App layout effect 
App effect 
mounted <div>App layout mounted;App mounted;</div> 
App2 layout effect 
App2 effect
mounted <div>App2 mounted;</div> 
```

but got

![image](https://user-images.githubusercontent.com/1667873/49262605-28121680-f482-11e8-9ec1-918ed2576a88.png)

[![Edit 3vv85q81x6](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/3vv85q81x6)

in regular test case with `useEffect`
1. render the component witch contains `useEffect` 
2. notify event or data to the listener/subscription is `useEffect`. (`triggerEvent` or `Subject.next`)
3. check the rendered (v)dom result

But now, `useEffect`'s callback not firing always in the same time, like case above.
sometimes the tests will broken:

1. worked: in `App`,  `setMount` both in `useLayoutEffect` and `useEffect`, we could get the expect rendered dom result: 
2. broken: in `App2`,  `setMount` only in `useEffect`, we could get the unexpect rendered dom result

So we have to use `useLayoutEffect` instead of `useEffect` in our codes.

**Comment by einarq** [comment]
I think this expected behavior. useLayoutEffect runs synchronously (which is what didMount and didUpdate did), whereas useEffect does not. So if you render a component that has a useEffect in a test, the effect won’t have run when the component is rendered.
This is mentioned in the docs. 

It is a shame though, since it kind of forces us to use useLayoutEffect if we want to test the effect callback as well. 
Or maybe there is another way to do it? 
Perhaps there could be a way to make useEffect be sync during testing? That might be a bad idea due to something I’m missing though.

**Comment by einarq** [comment]
I guess this issue will solve it for us:
https://github.com/facebook/react/issues/14050
